words:
  - avenir
  - clsx
  - esbuild
  - grayscale
  - hookz
  - lucide
  - Mingxuan
  - nodenext
  - reekystive
  - Vite
  - Vitest
  - WCAG
flagWords:
  - blacklist -> blocklist
  - whitelist -> allowlist
suggestWords:
  - colour -> color
ignorePaths:
  - cspell.config.yaml
